export { default as Photo1 } from './1.webp';
export { default as Photo2 } from './2.webp';
export { default as Photo3 } from './3.webp';
export { default as Photo4 } from './4.webp';
export { default as Photo5 } from './5.webp';
export { default as Photo6 } from './6.webp';
export { default as Photo7 } from './7.webp';
export { default as Photo8 } from './8.webp';
export { default as Photo9 } from './9.webp';
